### ISSUE TITLE
Need to determine outputs with the right CMSSW setup

### ISSUE THREAD

**Issue by matz-e** [NDCMS/lobster#317]
Right now, when we use Lobster with, e.g., `CMSSW_7_4_1`, but have not all output files specified in a config using a separate sandbox release, we may have an exception when loading a pset for, e.g., `CMSSW_8_0_X`, or for a release with a lot of custom packages, because python imports are missing.

We should create a little script that is executed within the sandbox environment and determines the output files there, and passes this back to Lobster (i.e. via subprocess). I think this relates to the discussion in #314.

**Comment by annawoodard** [comment]
Note also that automatic output file detection is currently not working when the config requires local auxiliary files (i.e., files the user specifies with `extra_inputs`). So those would have to be copied around too.

I'm torn-- I don't necessarily agree with this, but I think we should consider the possibility: since explicitly specifying the output file is not much trouble, it might be better to remove automatic output file determination, and keep Lobster simpler and easier to maintain, rather than add more complication to get it right.

**Comment by klannon** [comment]
How does automatic output file detection work?  I always assumed that the entries in `outputs` were found in the output directory and renamed after the job ran and then transferred to the output location.  Is there something more complicated/subtle being done?

**Comment by annawoodard** [comment]
@klannon: You can omit the `outputs` key in your Lobster configuration and Lobster will load your CMSSW configuration with [imp](https://docs.python.org/2/library/imp.html) and determine the output file from `process.outputModules`. It only works provided you only have one output file and (currently) that you don't require any local auxiliary files, and that you aren't running Lobster with a CMSSW version which is incompatible with the CMSSW config you want to run. Those caveats, along with the fact that we want to eventually de-couple CMSSW from Lobster, and also that specifying the output file explicitly isn't much trouble are why I think we should consider just removing this feature rather than fixing it.

**Comment by matz-e** [comment]
I for one rather enjoy the feature. I also don't think it's too much work fixing most use cases. For decoupling CMSSW from the workflow, we'd have to have `core.Workflow` and `cmssw.Workflow` anyways, so I think we should keep it.

**Comment by annawoodard** [comment]
Sounds good! I just thought I'd throw out a dissenting possibility. We should always consider the costs of features in terms of added complexity, even though usually the feature is worth the cost. :smile:

I think though that this should be lower in priority than, for example, #319, since one can always circumvent the bug by explicitly stating the output file.

**Comment by matz-e** [comment]
Note: this will also apply to the global tag for publishing, once #527 is merged.
